# Generated by Django 5.2.6 on 2025-09-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='progress_notes',
            field=models.TextField(blank=True, help_text='تسجيل التقدم المحقق نحو الهدف'),
        ),
        migrations.AddField(
            model_name='goal',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, help_text='نسبة التقدم (0-100%)'),
        ),
    ]
